x-defaults: &defaults
  restart: always
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "1M"

services:
  frontend:
    <<: *defaults
    image: skorpil/wedding-frontend:latest
    restart: always
    build:
      context: ./build/frontend
      target: prod
    environment:
      - 'MATOMO_URL=${MATOMO_URL}'
      - 'MATOMO_SITE_ID=${MATOMO_SITE_ID}'
      - 'TZ=${TIMEZONE}'
      - 'GRAPHQL_URL=http://payload:3000/api/graphql'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wedding-frontend.rule=Host(`${HOST}`)"
      - "traefik.http.routers.wedding-frontend.entrypoints=https"
      - "traefik.http.routers.wedding-frontend.tls=true"
      - "traefik.http.routers.wedding-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.wedding-frontend.loadbalancer.server.port=3000"
    networks:
      proxy:
      wedding:
    depends_on:
      - payload

  payload:
    <<: *defaults
    image: skorpil/wedding-payload:latest
    build:
      context: ./build/payload
      target: prod
    volumes:
      - payload-uploads:/home/node/app/uploads
    depends_on:
      - mongo
    networks:
      wedding:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wedding-payload.rule=Host(`${HOST}`)&&PathPrefix(`/admin`,`/api`,`/uploads`)"
      - "traefik.http.routers.wedding-payload.entrypoints=https"
      - "traefik.http.routers.wedding-payload.tls=true"
      - "traefik.http.routers.wedding-payload.tls.certresolver=letsencrypt"
      - "traefik.http.services.wedding-payload.loadbalancer.server.port=3000"
    environment:
      TZ: ${TIMEZONE}
      MONGODB_URI: mongodb://root:${MONGO_PASSWORD}@mongo:27017/admin
      PORT: 3000
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      SERVER_URL: https://${HOST}

  mongo:
    <<: *defaults
    image: mongo:latest
    networks:
      wedding:
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-data:/data/db
    environment:
      TZ: ${TIMEZONE}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

networks:
  wedding:
  proxy:
    external: true
    name: proxy
  mail:
    external: true
    name: mail

volumes:
  mongo-data:
  payload-uploads:
