services:
  frontend:
    image: skorpil/wedding-frontend:dev
    labels:
      - "traefik.http.routers.wedding-frontend.tls.certresolver=local"
    environment:
      NODE_ENV: development
    build:
      target: dev
    volumes:
      - ./build/frontend/application:/srv
  payload:
    image: skorpil/wedding-payload:dev
    build:
      target: dev
    volumes:
      - ./build/payload/application:/home/node/app
      - ./build/payload/application/node_modules:/home/node/app/node_modules
    labels:
      - "traefik.http.routers.wedding-payload.tls.certresolver=local"
  mongo:
    ports:
      - "27017:27017"
